routes.py
from flask import Blueprint, render_template, redirect, url_for, request, flash, session
from werkzeug.security import generate_password_hash, check_password_hash
from models import User
from flask_login import login_user, logout_user, login_required
from config import db

routes = Blueprint('routes', __name__)  # Blueprint object for routes


@routes.route('/login', methods=['GET', 'POST'])  # path for login page
def login():  # define login page function
    if request.method == 'GET':  # if the request is a GET we return the login page
        return render_template('login.html')
    else:  # if the request is POST then we check if the user exist and with te right password
        email = request.form.get('email')
        password = request.form.get('password')
        remember = True if request.form.get('remember-me') else False
        user = User.query.filter_by(email=email).first()  # check if the user actually exists
        # take the user-supplied password, hash it, and compare it to the hashed password in the database

        if not user:
            return redirect(url_for('views.user_type'))
        elif not check_password_hash(user.password, password):
            flash('Please check your login details and try again.')
            return redirect(url_for('routes.login'))  # if the user doesn't exist or password is wrong, reload the page
        # if the above check passes, then we know the user has the right credential's
        session['id'] = user.id

        login_user(user, remember=remember)
        if user.user_role == 'patient':
            return redirect(url_for('views.index_user'))
        elif user.user_role == 'doctor':
            return redirect(url_for('views.index_doctor'))
        elif user.user_role == 'pharmacist':
            return redirect(url_for('views.index_pharmacist'))
        elif user.user_role == 'admin':
            return redirect(url_for('views.index_admin'))
        else:
            return redirect(url_for('views.user_type'))


@routes.route('/signup', methods=['GET', 'POST'])  # we define the sign up path
def signup():  # define the signup function
    if request.method == 'GET':  # If the request is GET we return the sign up page and forms
        return redirect(url_for('views.user_type'))
    else:  # if the request is POST, then we check if the email doesn't already exist and then we save data
        name = request.form.get('fullname')
        email = request.form.get('email')
        password = request.form.get('password')
        gender = request.form.get('gender')
        dob = request.form.get('dob')
        street = request.form.get('street')
        city = request.form.get('city')
        state = request.form.get('state')
        county = request.form.get('county')
        address = ''
        if street:
            address += street
        if city:
            address += ', ' + city
        if state:
            address += ', ' + state
        if county:
            address += ', ' + county + '.'
        mobile = request.form.get('mobile')
        user_type = "patient"
        # For Doctor registration
        position = request.form.get('position')
        category = request.form.get('category')
        # For Pharmacist Registration
        pharmacy_reg_no = request.form.get('pharmacy_reg_no')
        secret_key = request.form.get('secret_key')
        user = User.query.filter_by(email=email).first()  # return user if email already exist
        if user:  # if that user already registered return again to sign up page
            return redirect(url_for('views.user_type'))

        if position and category:
            user_type = "doctor"
            check_doc = User.query.filter_by(secret_key=secret_key).order_by(User.id.desc()).first()
            if check_doc:
                # db.engine.execute("""UPDATE user SET full_name=%s, email=%s, password=%s WHERE id=%s""", name, email,
                #                   generate_password_hash(password), check_doc.id)
                check_doc.full_name = name
                check_doc.email = email
                check_doc.password = generate_password_hash(password)
                check_doc.mobile = mobile
                check_doc.position = position
                check_doc.category = category
                check_doc.address = address
                db.session.commit()
            else:
                flash('Wrong Secret Key!')
                return redirect(url_for('views.signup_doctor'))
        if pharmacy_reg_no:
            user_type = "pharmacist"

        # create a new user with the form data. Hash the password so the plaintext version isn't saved.
        new_user = User(full_name=name, email=email, password=generate_password_hash(password), gender=gender, dob=dob,
                        address=address, mobile=mobile, position=position, category=category,
                        pharmacy_reg_no=pharmacy_reg_no, user_role=user_type, secret_key=secret_key)
        # add the new user to the database
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('routes.login'))


@routes.route('/logout')  # path for logout
@login_required
def logout():  # function for logout action
    logout_user()
    return redirect(url_for('views.index'))


@routes.route('/index')
def index():
    return redirect(url_for('views.index'))

views.py
from flask import Blueprint, render_template, request, flash, jsonify, session, redirect, url_for
from flask_login import login_required
from config import db
from datetime import datetime, date
import routes
from models import User, ProductStock, Product

views = Blueprint('views', __name__)


@views.route('/')
# login page that return 'login'
def index():
    return render_template('index.html')


@views.route('/user-type')
# user can select user type in this page
def user_type():
    return render_template('account_type.html')


@views.route('/signup-doc')
# Return view for normal user
def signup_doctor():
    return render_template('signup_doctor.html')


@views.route('/signup-phar')
# When a pharmacist sign up into system
def signup_pharmacist():
    return render_template('signup_pharmacist.html')


@views.route('/signup-usr')
# When a normal user try to sign up
def signup_user():
    return render_template('signup_user.html')


@views.route('/admin')
@login_required
def index_admin():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'admin':
        return render_template('admin.html')
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/admin/add-doctor', methods=['GET', 'POST'])
@login_required
def admin_add_doctor():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'admin':
        if request.method == 'GET':
            return render_template('admin.html')
        else:
            secret_key = request.form.get('secretkey')
            name = request.form.get('name')
            role = 'doctor'
            doctor = User.query.filter_by(secret_key=secret_key).first()
            if doctor:
                flash("Secret key already in used!")
                return redirect(url_for('views.index_admin'))
            else:
                new_doctor = User(full_name=name, email=None, password=None, gender=None, dob=None, address=None,
                                  mobile=None, position=None, category=None,
                                  pharmacy_reg_no=None, user_role=role, secret_key=secret_key)
                db.session.add(new_doctor)
                db.session.commit()
                return redirect(url_for('views.index_admin'))
    else:
        return redirect(url_for('views.page_not_found'))


# Routes for doctors
@views.route('/doctor')
@login_required
# Doctor profile
def index_doctor():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'doctor':
        return render_template('doctor_profile.html', name=user.full_name, category=user.category)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/doctor/appointments')
@login_required
def doctor_appointments():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'doctor':
        return render_template('doctor_profile_appointments.html', name=user.full_name, category=user.category)
    else:
        return redirect(url_for('views.page_not_found'))


# Routes for Patients
@views.route('/user')
@login_required
# Doctor profile
def index_user():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        return render_template('patient_menu.html', name=user.full_name)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/user_details')
@login_required
def user_profile_details():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    age = date.today().year - user.dob.year
    if user.user_role == 'patient':
        return render_template('patient_profile_settings.html', name=user.full_name, age=age, gender=user.gender)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/chat')
@login_required
def chat():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        return render_template('chatUi.html')
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/doctor')
@login_required
def doctor_for_user():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        return render_template('user_doctor_profile.html')
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/buy-med', methods=['GET', 'POST'])
@login_required
def buy_medicine():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        if request.method == 'GET':
            return render_template('patient_buy_medicine.html', name=user.full_name)
        else:
            # TODO: place an order, store in table
            pass
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/appointment')
@login_required
def place_appointment():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        return render_template('appointment_booking.html', name=user.full_name, phone=user.mobile)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/user/location')
@login_required
def get_location():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'patient':
        """Get longitude and latitude of user"""
        import location as loc
        loc.inputs()
        loc.makeMap()
        loc.add_CSV_values_to_map()
        loc.add_user()
        loc.draw_circle_around_user()
        return render_template('map.html')
    else:
        return redirect(url_for('views.page_not_found'))


# Routes for Pharmacists
@views.route('/pharmacist')
@login_required
def index_pharmacist():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'pharmacist':
        return render_template('pharmacy_profile.html', name=user.full_name)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/pharmacist/sales')
@login_required
def sale_order_details():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'pharmacist':
        return render_template('pharmacy_sales.html', name=user.full_name)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/pharmacist/inventory', methods=['GET', 'POST'])
@login_required
def pharmacy_inventory():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'pharmacist':
        if request.method == 'GET':
            """This part only set records for table content of inventory"""
            # view records of inventory(product stock)
            pass
        else:
            """This will be called when user try to update or delete records"""
            if request.form.get('update') == 'update':
                id = request.form.get('id')
                price = request.form.get('price')
                quantity = request.form.get('quantity')
                expire_date = request.form.get('expire_date')
                # update inventory record
                product_stock = ProductStock.query.filter_by(id=id).first()
                product_stock.price = float(price)
                product_stock.quantity = int(quantity)
                product_stock.expire_date = datetime.strptime(expire_date, '%Y-%m-%d').date()
            elif request.form.get('update') == 'delete':
                id = request.form.get('id')
                product_stock = ProductStock.query.filter_by(id=id).first()
                db.session.delete(product_stock)
            db.session.commit()

        inventory_records = ProductStock.query.filter_by(pharmacy_id=user.id).order_by(ProductStock.id.asc())
        record_list = []
        for inventory_record in inventory_records:
            records = {}
            product = Product.query.filter_by(id=inventory_record.product_id).first()
            records['id'] = inventory_record.id
            records['product'] = product.name
            records['price'] = inventory_record.price
            records['quantity'] = inventory_record.quantity
            records['brand'] = inventory_record.brand
            records['expire_date'] = inventory_record.expire_date
            record_list.append(records)
        return render_template('pharmacy_inventory.html', name=user.full_name, record_list=record_list)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/pharmacist/inventory/update', methods=['POST', 'GET'])
@login_required
def inventory_update():
    user_id = session.get('id')
    user = User.query.filter_by(id=user_id).first()
    if user.user_role == 'pharmacist':
        products = Product.query.all()
        if request.method == 'POST':
            """update database"""
            product = request.form.get('product')
            price = request.form.get('price')
            quantity = request.form.get('quantity')
            brand = request.form.get('brand')
            expire_date_str = request.form.get('expire_date')
            expire_date = datetime.strptime(expire_date_str, '%Y-%m-%d').date()
            stock_rec = ProductStock(quantity=int(quantity), price=float(price), product_id=int(product),
                                     pharmacy_id=user.id, brand=brand, expire_date=expire_date)
            db.session.add(stock_rec)
            db.session.commit()
        return render_template('inventory_update.html', products=products)
    else:
        return redirect(url_for('views.page_not_found'))


@views.route('/page-not-found')
def page_not_found():

templates/Inventory.html
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
<link rel="stylesheet" href="Inventory.css">

<h1 id="title">Inventory</h1>
        <hr>

<form>
    <div class="mb-3">
      <label for="InputProduct" class="form-label">Product</label>
      <input type="text" class="form-control" id="InputProduct" aria-describedby="productHelp">
    </div>
    <div class="mb-3">
      <label for="InputBrand" class="form-label">Brand</label>
      <input type="text" class="form-control" id="InputBrand">
    </div>
    <div class="mb-3">
        <label for="InputQuantity" class="form-label">Quantity</label>
        <input type="number" class="form-control" id="InputQuantity">
      </div>
      <div class="mb-3">
        <label for="InputPrice" class="form-label">Price</label>
        <input type="number" class="form-control" id="InputPrice">
      </div>
    <button type="submit" class="btn btn-primary" id="btn-submit">Submit</button>
  </form>

templates/PharmacyProfile.html
<!DOCTYPE html>
<html>
    <head>
        <title>Wheres Pharmacy</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
        <link rel="stylesheet" href="PharmacyProfile.css">
    </head>
    <body>
        <h1 id="title">Pharmacy Profile</h1>
        <hr>
        
        <div id="icon-row-box" class="container centerbox">
            <div class="icon-row">
                <a href="https://www.example.com">
                    <img class="icons" src="Bell.png" alt="Icon 1">
                </a>
                <a href="https://www.example.com">
                    <img class="icons" src="tele.png" alt="Icon 2">
                </a>
                <a href="https://www.example.com">
                    <img class="icons" src="msg.png" alt="Icon 3">
                </a>
            </div>
        </div>
          
        <div class="container">

            <a href="Pharmacy_Sales.html">
                <div class="row big-button">
                    <!--text-->
                    <div class="col text-container centerbox">
                        <p>Sales</p>
                    </div>
                    <!--image-->
                    <div class="col-7 image-container"><img class="button-image" src="sales2.png" alt="sales"/></div>
                </div>
            </a>

            <a href="Pharmacy_Inventory.html">
                <div class="row big-button">
                    <!--text-->
                    <div class="col text-container centerbox">
                        <p>Manage Inventory</p>
                    </div>
                    <!--image-->
                    <div class="col-7 image-container"><img class="button-image" src="Inventory.png" alt="inventory"/></div>
                </div>
            </a>

        </div>
    </body>
</html>

templates/account_type.html
<html>
<head>

    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Account Type</title>
    <link href="https://fonts.googleapis.com/css2?family=Roboto&display=swap" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/account_type.css') }}" rel="stylesheet">
    <link rel="stylesheet"
          href="{{ url_for('static', filename='fonts/material-icon/css/material-design-iconic-font.min.css') }}">

</head>

<body>
<h1 class="form-title">Select Account Type</h1>
<div class="leftside">
    <a href="{{ url_for('views.signup_user') }}">
        <div class="labelexpanded">
            <div class="radio-btns">
                <img src="{{ url_for('static', filename='images/type-user.png') }}"/>
                <p> Patient </p>
            </div>
        </div>
    </a>

    <a href="{{ url_for('views.signup_pharmacist') }}">
        <div class="labelexpanded">
            <div class="radio-btns">
                <img src="{{ url_for('static', filename='images/type-pharmacy.png') }}"/>
                <p> Pharmacy </p>
            </div>
        </div>
    </a>

    <a href="{{ url_for('views.signup_doctor') }}">
        <div class="labelexpanded">
            <div class="radio-btns">
                <img src="{{ url_for('static', filename='images/type-doctor.png') }}"/>
                <p> Doctor </p>
            </div>
        </div>
    </a>
</div>
</body>

</html>

templates/doctor_profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Doctor Profile</title>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/doctor_profile.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/logout.css') }}">
</head>
<body style="background-color: #bee0ec;">
<div class="logocaption"><h2>{{name}}</h2></div>
<div class="caption text-left">{{category}}</div>
<h1>Doctor Profile</h1>
<div class="profile-photo">
    <!--    <form action="{{ url_for('routes.logout') }}" method="post">-->
    <!--        <button type="submit" style="">Logout</button>-->
    <!--    </form>-->
    <img class="profile-pic" src="{{ url_for('static', filename='images/profile_image.jpg') }}"
         alt="Doctor profile" onmouseover="showMenu()" onmouseout="hideMenu()">
    <div id="dropdown-menu" class="dropdown-menu" style="margin-top: -25px; margin-right: 40px; width: 70px;">
        <a href="{{url_for('routes.logout')}}" onclick="logout()">Logout</a>
    </div>
</div>

<!--<div class="time">-->
<!--    <h4>Patient time: 8AM -10PM</h4>-->
<!--</div>-->

<div class="wrapper">
    <div class="wrapper">
        <input type="radio" name="rate" id="rate1">
        <label for="rate1"></label>
        <input type="radio" name="rate" id="rate2">
        <label for="rate2"></label>
        <input type="radio" name="rate" id="rate3">
        <label for="rate3"></label>
        <input type="radio" name="rate" id="rate4">
        <label for="rate4"></label>
        <input type="radio" name="rate" id="rate5">
        <label for="rate5"></label>
    </div>
</div>

<div id="icon-row-box" class="container centerbox">
    <div class="icon-row">
        <a href="#">
            <img class="icons" src="{{ url_for('static', filename='images/tele.png') }}" alt="contact">
        </a>
        <a href="#">
            <img class="icons" src="{{ url_for('static', filename='images/msg.png') }}" alt="message">
        </a>

    </div>
</div>
<div class="outer"style="border-color: #BEE0EC">
    <div class="card">
        <img src="{{ url_for('static', filename='images/patient.jpg') }}" class="card-img-top"
             alt="Successful patients"/>
        <div class="card-body">
            <h1 class="card-title">500+</h1>
            <p class="card-title">Successful patients</p>
        </div>
    </div>
    &nbsp;
    <a href="{{ url_for('views.doctor_appointments') }}">
        <div class="card">
            <img src="{{ url_for('static', filename='images/patient2.png') }}" class="card-img-top"
                 alt="Today's Appointments"/>
            <div class="card-body">
                <h1 class="card-title">49</h1>
                <p class="card-title">Today's Appointments</p>
            </div>
        </div>
    </a>

</div>
<script src="{{ url_for('static', filename='js/logout.js') }}"></script>
</body>
</html>

templates/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- CSS file for index -->
    <link rel="stylesheet" href="{{url_for('static', filename='css/index.css')}}">

    <title>Wheres Pharmacy</title>
</head>

<body>
    <div class="container">
        <header class="head my-3">
            <nav class="navbar navbar-expand-lg navbar-light head__custom-nav">
                <a class="navbar-brand d-flex align-items-center" href="{{ url_for('views.index') }}">
                    <img src="{{ url_for('static', filename='images/wheres-pharmacy-logo.png')}}" alt="website logo">
                    <span>Where's Pharmacy</span>
                </a>
<!--                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">-->
<!--                    <ul class="navbar-nav">-->
<!--                        <li class="nav-item">-->
<!--                            <div>-->
<!--                                <a class="btn btn-primary" href="{{ url_for('routes.signup')}}" role="button">REGISTER</a>-->
<!--                            </div>-->
<!--                        </li>-->
<!--                        <li class="nav-item">-->
<!--                            <div>-->
<!--                                <a class="btn btn-primary" href="{{ url_for('routes.login')}}" role="button">LOG IN</a>-->
<!--                            </div>-->
<!--                        </li>-->
<!--                    </ul>-->
<!--                </div>-->
            </nav>
        </header>
    </div>
    <div class="container">
        <div class="row custom-section d-flex align-items-center">
            <div class="col-12 col-lg-4">
                <h2>Healthcare</h2>
                <h3>Anywhere</h3>
                <h3>Anytime</h3>
                <p>Find a Pharmacy and a doctor in one place</p>
                <a style="border-radius: 10px;" href="{{ url_for('views.user_type') }}">Sign Up</a>
                <a style="border-radius: 10px;" href="{{ url_for('routes.login') }}">Log In</a>
            </div>
            <div class="col-12 col-lg-8" id="landing-container-img">
                <img src="{{url_for('static', filename='images/background.jpg')}}" alt="Where Pharmacy Home">
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

templates/inventory_update.html
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/inventory.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/common_actions.css') }}">
    <title>Inventory</title>
</head>
<body>
<div class="title-top">
    <div>
        <a href="{{ url_for('views.pharmacy_inventory') }}">
            <img src="{{ url_for('static', filename='images/left-arrow.png') }}">
        </a>
    </div>
    <div class="title-head"><h1 id="title">Inventory</h1></div>
</div>
<hr>

<div>
    <form action="{{ url_for('views.inventory_update') }}" method="post">
        <div class="mb-3">
            <label for="product" class="form-label">Product</label>
            <select name="product" id="product" class="form-control" aria-describedby="productHelp">
                <option></option>
                {% for product in products %}
                <option value="{{ product.id }}">{{ product.name }}</option>
                {% endfor %}
            </select>
        </div>
        <div class="mb-3">
            <label for="brand" class="form-label">Brand</label>
            <input type="text" class="form-control" id="brand" name="brand">
        </div>
        <div class="mb-3">
            <label for="quantity" class="form-label">Quantity</label>
            <input type="number" class="form-control" id="quantity" name="quantity">
        </div>
        <div class="mb-3">
            <label for="price" class="form-label">Price</label>
            <input type="number" step="0.01" class="form-control" id="price" name="price">
        </div>
        <div class="mb-3">
            <label for="expire_date" class="form-label">Expire Date</label>
            <input type="date" id="expire_date" name="expire_date" placeholder="Expire Date"/>
        </div>
        <button type="submit" class="btn btn-primary" id="btn-submit">Create</button>
    </form>
</div>
</body>

templates/patient_buy_medicine.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="{{ url_for('static', filename='css/patient_menu.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/patient_buy_medicine.css') }}" rel="stylesheet">
    <title>Buy Medicine</title>
</head>
<body>

<div class="container-fluid">

    <h1>{{name}}</h1>


</div>
<hr>
<section class="vh-100">
    <div class="container-fluid h-custom">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col-md-9 col-lg-6 col-xl-5">
                <img src="https://woxapp.com/uploads/images/1_Preview_on_demand.png"
                     class="img-fluid" alt="Sample image">
            </div>
            <div class="col-md-10 col-lg-6 col-xl-4 offset-xl-1">

                <h4 class="mb-6">Order Medicine</h4>

                <form method="post" action="{{ url_for('views.buy_medicine') }}">
                    <div class="row">
                        <div class="form-outline mb-6">
                            <label class="form-label" for="form6Example3">Medicine Name</label>
                            <input type="text" id="form6Example3" class="form-control"/>
                        </div>
                        <div class="form-outline mb-6">
                            <label class="form-label" for="form6Example4">Brand</label>
                            <input type="text" id="form6Example4" class="form-control"/>
                        </div>
                        <div class="col-12 col-md-6 mb-6">
                            <div class="form-outline">
                                <label class="form-label" for="form6Example2">Quantity</label>
                                <input type="text" id="form6Example2" class="form-control"/>
                            </div>
                        </div>
                    </div>
                    <div class="form-outline mb-3">
                        <label class="form-label" for="form6Example7">Additional information</label>
                        <textarea class="form-control" id="form6Example7" rows="4"></textarea>
                    </div>

                    <button type="submit" class="btn btn-secondary btn-rounded btn-block" >Place order</button>
<!--                    <button type="submit" class="btn btn-secondary btn-rounded btn-block">Check Availability</button>-->
<!--                    <button type="submit" class="btn btn-secondary btn-rounded btn-block">Add to Cart</button>-->
<!--                    <button type="submit" class="btn btn-secondary btn-rounded btn-block">Show Pharmacy List</button>-->
                </form>
            </div>
        </div>
    </div>
    </div>
</section>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
</body>
</html>